name: Github Action

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin (AdoptOpenJDK)
          java-version: '17' # Specify Java version (modify as needed)

      # Step 3: Install dependencies and run tests
      - name: Run Maven Tests
        run: 
          mvn clean test
